shortener/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'url'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('create/', views.urlShort, name='shorten-url'),
                  path('<str:pk>', views.urlRedirect, name='redirected-url')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlshortener/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shortener/models.py
from django.db import models


# Create your models here.

class UrlShortener(models.Model):
    longurl = models.URLField(max_length=225, blank=False)
    shorturl = models.CharField(max_length=30)

    def __str__(self):
        return self.shorturl

urlapi/models.py
from django.db import models


# Create your models here.

class UrlShortener(models.Model):
    longurl = models.URLField(max_length=225)
    shorturl = models.CharField(max_length=30)

    def __str__(self):
        return self.shorturl

shortener/views.py
import random
import string

from django.shortcuts import render, redirect, get_object_or_404

from .models import UrlShortener


def urlShort(request):
    if request.method == 'POST':
        shorturl = ''.join(random.choice(string.ascii_letters)
                           for x in range(5))
        short = 'https://my-url.up.railway.app/' + shorturl
        longurl = request.POST['link']
        new_url = UrlShortener(longurl=longurl, shorturl=short)
        new_url.save()
        return render(request, 'index.html', context={'shorturl': short})

    data = UrlShortener()
    context = {
        'data': data
    }
    return render(request, 'index.html', context)


def urlRedirect(request, pk):
    data = get_object_or_404(UrlShortener, shorturl="https://my-url.up.railway.app/" + pk)
    return redirect('https://' + data.longurl)


def index(request):
    return render(request, 'index.html')

shortener/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>My Url Shortener</title>
        <link rel="stylesheet" href="{% static 'shortener/index.css' %}" type="text/css">
    </head>
    <body>
        <main>
            <h1>URL Shortener</h1>
            <form method="post" action="{% url 'url:shorten-url' %}">
            {% csrf_token %}
            <input type="text" name="link" id="longurl" placeholder="Enter URL here" required>
            <div class="buttons">
            <button type="submit" id="shorten">Shorten</button>
            </div>
            </form>

            <section id="section"><h2>{{ shorturl  }}</h2></section>

        </main>

    </body>
</html>